name:                one
version:             0.1.0.0
github:              "shawa/one"
license:             BSD3
author:              "shawa"
maintainer:          "git@github.com"
copyright:           "2018 shawa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/shawa/one#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- parsec-numbers
- unique
- containers

library:
  source-dirs: src

executables:
  one-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - one

tests:
  one-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - one
